Bartek Waszczyk, wykonane zadania.
t0meck-pj/ukos2023-24_14c pull request #28
Opened 2023-12-09 08:30 UTC by s32351-pj

Proszę o merdż. Zadania.

2023-12-12 23:20 UTC, t0meck-pj requested changes
Na tę chwilę ustawię status że wymaga zmian bo znaczna część jest ok ale te zadania wykonywane na windowsie mnie ku temu skłoniły by poczekać jeszcze z mergeowaniem.

Proszę przeczytać wszystkie opisy oraz zapoznać się z zasadami używania repozytorium.
Proszę docommitować zmiany i wtedy sprawdzę co jeszcze tu trzeba dalej poprawić.
W pamiętniku zostawiłem komentarz o uzyskiwaniu podwyższonych uprawnień. Proszę sprawdzić w Internecie jakie to proste i faktycznie poszukać uzasadnienia (być może na superuser/poweruser lub serverfault bądź innych temu podobnych) dlaczego zbyt wysokiem uprawnienia są złe.
Poproszę gdzieś i pozostawienie linków do takich znalezisk. Przydadzą się na kolejne zajęcia (dla następnego rocznika) + będą dobrym tematem do poszerzenia swojej wiedzy i świadomości o uprawnieniach.

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/1_Wstep do konsoli_zadania_1.txt
> + - A włączyłem midnight commander, skrót mc. Acha, ćwiczymy CLI, no to exit (żeby wyjść z MC) i potem na przykład: ls -lA. Duże A, żeby nie było kropeczek.
F10

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/1_Wstep do konsoli_zadania_1.txt
> + - no sprawdzam, pwd. odpowiedź: /home/PJWSTK/s32351, no nie dziwne, to mój katalog domowy na Szuflandii. Hejkum-Kejkum!
... Olo ratuj!

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/1_Wstep do konsoli_zadania_1.txt
> + - dochodzę do wniosku, że na szuflandii nie ma katalogu Pulpit. sprawdzam na wszelki upadek, a nuż ktoś dla zabawy wrzucił. MC. a nie, wychodzę z MC, wpisuję find Pulpit. nie wiem jaki param dla ign
Dobrze... no to tak:
Opis fajny ALE...
PRIMO!
https://github.com/t0meck-pj/ukos2023-24_14c/blob/master/README.md - zapoznać się z tekstem i poprawić ten wiersz oraz jak widzę sporo kolejnych

Po co grzebać po opcjach find skoro poprzednie polecenie listowało wszystkie katalogi i tam można było sprawdzić czy takowy "Pulpit" istnieje?
Dobrze, że próbowałeś. To się liczy. No i próbowałeś nowego narzędzia. Ale zwróć uwagę, że szuflandia to serwer z domyślnym językiem angielskim więc zamiast "Pulpit" mógł się pojawić katalog z angielską nazwą. Jak wspominałem na zajęciach: Na tym przedmiocie trzeba myśleć!

Anyways.. faktycznie dla nowych studentów już może takiego katalogu nie być.
Nie korzystacie ze srodowiska graficznego więc to zrozumiałe.

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/1_Wstep do konsoli_zadania_1.txt
> +- alt+F7 powinno wrócić do konsoli X servera. Tak w internetach piszą, bo u mnie nie działa. Chyba muszę tego linuch już zainstalować......
Po przeczytaniu tego pliku sam nie wiem co mam o nim myśleć.
Z jednej strony fajnie się to czyta bo jest pisane luźnym językiem.
Z drugiej strony to trochę brak szacunku kiedy student pisze "nie chce mi się" lub pomimo świadomości, że zajęcia skupione są na linuxie to usilnie student używa jakiś wytrychów na windowsie typu cygwin czy pochodnych by wykonać zadania. Jest przewidziany program zajęć i warto by było go wykonać by czegoś się nauczyć bo w przeciwnym wypadku co te zajęcia mają Tobie dać? Przesiedzenie n godzin i odwalenie zadań by zaliczyć tylko przedmiot? To gdzie tu sens? Przecież na zajęciach mamy cały czas rzeczy praktyczne pokazywane przed którymi zapewnie nie uciekniesz.

Zatem proszę by zadania 5-9 były wykonane ponownie na linuxie.
Formę opisu możesz pozostawić luźną. Jak wspomniałem fajnie się to czyta.

Zadanie 10 zaktualizuj odpowiedź w ostatnim wierszu

Zadanie 12: Aktualne opisy z AWS-em proszę pozostaw.
Ewentualnie dodaj opis dlaczego wykonywałeś tyle różnych operacji, instalowałeś cli do zarządzania infrastrukturą w chmurze, generowałeś klucze itd... zamiast podłączyć się do szuflandii i tam wykonać tę prostą operację?

Zadanie 13 i 14 wymaga terminala lokalnego więc pełna lokalna VM raczej będzie wskazana.

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/1_Wstep do konsoli_zadania_2.txt
> +- touch ukos/klamka/zajęcia2.txt && touch ukos/klamka/zajecia2.log && touch ukos/klamka/inny.txt && touch ukos/klamka/nowy.txt. Znownu tree /home - są pliki.
Czy touch może przy pojedynczym wywołaniu tworzyć tylko jeden plik?

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/1_Wstep do konsoli_zadania_2.txt
> +- no z parametrem -p a w katalogu ukos... powstanie wtedy drugi ukos/... zgodnie z tym jak zapisane jest to polecenie. (jestem w domowym wciąż) mkdir -p ukos/ukos/to/jest/długa/nazwa. tree /home:
Dobrze ale pamiętamy o czym była mowa w README.md ?

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/1_Wstep do konsoli_zadania_2.txt
> +-man rmdir, tak samo jak przy mkdir, przełącznik -p. czyli rmdir... a nie jest inny, ale ten -p też się porzyda, zatem: rmdir -p --ignore-fail-on-non-empty ukos/klamka. poszło. ale zaraz, nie działa.
I jeszcze raz: README.md

A o rekurencji pieśni starszych kiedyś nie wspominały?

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/2_Uprawnienia dostepu_zadania.txt
> +-bash: ./m/plik.txt: Brak dostępu. nadaję sobie prawo do zapisu : chmod u+w ./m/plik.txt ponawiam próbę zapisu. s -lA ./m>>./m/plik.txt - błąd, nie mam dostępu do /m, zatem przechodzę katalogu powyże
- Raz prawo a raz
- ... "lewo" ?
- Nie. Nie lewo.
- To co? 
- Uprawnienie. 
- Aha... 
- No to teraz trzeba poprawić tam gdzie jest niespójnie i źle.
- Łeee

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/2_Uprawnienia dostepu_zadania.txt
> +Może inaczej: maska binarnie; negacja potem w porónaniu z bitami aktualnych uprawnienia do pliku; koniunkcji da zmienione uprawnieni tworzonych plików.
👍 
README.md

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/2_Uprawnienia dostepu_zadania.txt
> +- umask, będąc maską, nadaje uprawnienia niejako odwrotnie do chmod, a poza tym jest ustawieniem stałym. Operacja wykonywana to negacja bitów uprawnień, na przykład chmod 700 nadaje pełne uprawnienia
README.md

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/3_Procesy i strumienie_zadania.txt
> +- tyle ile ich mam, znaczy 18 plikó, w tym katalogi, ale katalogi to też pliki, nieprawdaż?
Nie tak głośno! Przecież to tajne! :-)

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/3_Procesy i strumienie_zadania.txt
> +> - przekierowanie strumienia wyjściowego aplikacji do tam gdzie chcemy, plik, inna aplikacja, inny strumień (to z &) i tak dalej.
inna aplikacja?

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/3_Procesy i strumienie_zadania.txt
> +- ps -eC bash
🥇 
Pierwszy student. który wykonał to zadanie poprawnie.

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/3_Procesy i strumienie_zadania.txt
> +- kill w sensie SIGTERM, czy kill z innym sygnałem? Powinien zadziałać, o ile dany sygnał nie jest przejmowany w procesie.
zabij proces innego usera

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/3_Procesy i strumienie_zadania.txt
> +- na pewno nie wynikiem/rezultatem. Chyba, że miało się stać coś innego?
Istotnie. Miało się stać coś innego.
CTRL+C -> pusty plik
CTRL+D -> to co zostało wpisane bez znaku złamania wiersza.

Wnioski jeden przerywa program a drugi daje znać, że nie ma więcej danym i z tego powodu cat kończy swoją pracę drukując wszystko na terminal a z uwagi na to, że bash miał przekierowanie to bash przekierowuje wynik z terminala do pliku.

Ale mimo wszystko to przećwiczenie jeszcze raz.

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/4_kolokwium_powtorzenie_zadania.txt
> +
Zbędne interlinie

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/4_kolokwium_powtorzenie_zadania.txt
> +- mv /tmp/ukos/kot/ma/ale /tmp/ukos/ala/i
Tu jest absolutna i absolutna

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/4_kolokwium_powtorzenie_zadania.txt
> +- mv ../../../kot/ma/ale /tmp/ukos/ala/i
a to jest odpowiedź na poprzednie zadanie/przykład.

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/4_kolokwium_powtorzenie_zadania.txt
> +- można find . -type f -name "al*", albo ls al*
a może jakiś limit głębokości? find domyślnie szuka do oporu wgłąb

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/4_kolokwium_powtorzenie_zadania.txt
> +- chmod ua-r,g+r
a zawiera w sobie u. Nie trzeba go łączyć.
poza tym tylko odbierasz uprawnienia wszystkim i nadajesz do grupy. A gdzie pozostałe bity?

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/4_kolokwium_powtorzenie_zadania.txt
> +- chmod u=rwx
super. A pozostałe bity? grupa? inni?

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/4_kolokwium_powtorzenie_zadania.txt
> +- app a potem: bg
o czym zapomniałeś ?

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/pamietnik.txt
> +Hmmm. Cudnie, bardzo lubię ćwiczenia w terminalu. Zawsze kojaerzyło mi się i nadal kojarzy z posiadaniem wiedzy tajemnej, któa pozwala na robienie cudów. Oczywiście prócz romnantyzmu hakerstwa, prakt
README.md

2023-12-12 23:20 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/pamietnik.txt
> +dziś - uprawnienia. Temat mi znany baaaardzo 'po łebkach' jak dotąd; od teraz wiem już jak i co zmieniać, żeby całkowicie się zakopać w katalogu, do którego uprawnień żadnych nie mam, tak jak i do na
Na niestrawności proponuję wizytę u gastrologa :D
A na poważnie:
ServiceNOW... been there... seen it... went over it.
Osobiście także lubię Sublime Text.

Irytacja wynika z braku wygody a wygoda prawie zawsze jest przeciwieństwem bezpieczeństwa.
Przykład:
- jak uzyskać podwyższone uprawniena less-em
- jak uzyskać podwyższone uprawniena vim-em
- jak działa setuid i stickybit-em?
- dlaczego partycję hibernacji i wymiany należy szyfrować jeśli już zabieramy się za szyfrowanie danych?
- dlaczego nie należy rzeczy uruchomionych w kontenerach uruchamiać jako root na kontenerze?

Na te i wiele innych pytań administratorzy znają dobre przykłady i wyjaśnienia.
Ostatecznie nie wzięła się z nikąd ta sugestia by nadawać minimalne uprawnienia/prawa.

2023-12-13 21:45 UTC, s32351-pj commented
Dzień dobry!

Za powitaniem kryje się myśl, że praca w nocy jest nam (szeroko pojętemu
IT) bliska. Jedna kwestia wymaga wyjaśnienia, pozwolę sobie użyć wklejki, z
góry prosząc o wybaczenie:
[image: image.png]
- "nie chce mi się", bo jestem leniwy, a jak uzgodniliśmy, dobry
administrator jest leniwy. Ja nie wiem jeszcze jaką specjalizację przyjdzie
mi wybrać, niemniej taki był 'wytrych' do użycia tych słów.
- student usilnie używa wytrychów, bo wydaje mu się, że jest taki mądry.
Oczywiście nie jest, przyznaję z pokorą.
- przesiedzenie n godzin i zzz (zakuć, zaliczyć, zapomnieć)... UKOS?
Najciekawsze jak dotąd zajęcia na roku!? Nigdy. Bez wazeliny. Czasem po
prostu trudno się pozbyć starych nawyków (typu wytrychy), program zajęć zaś
jest dla mojej wiedzy jak nowy asfalt na dziurawą drogę. Moją drogą
dojadę do celu, może kilka plomb zgubię, a nowa nawierzchnia potrzebuje
czasu na położenie. Ale jest WIP! (Work In Progress).
- ale na poważnie - Jeżeli przeszkadza Panu nadmierna swoboda mojej
wypowiedzi, budzi nieufność lub dyskomfort, jestem gotów z niej niniejszym
zrezygnować.

No to zabieram się do poprawek. Jak rozumiem, wzmianki o readme.md związane
są z 80-ma znakami?

Pozostaję z szacunkiem,
Bartosz Waszczyk
Student.

śr., 13 gru 2023 o 00:21 t0meck-pj ***@***.***> napisał(a):

> ***@***.**** requested changes on this pull request.
>
> Na tę chwilę ustawię status że wymaga zmian bo znaczna część jest ok ale
> te zadania wykonywane na windowsie mnie ku temu skłoniły by poczekać
> jeszcze z mergeowaniem.
>
> Proszę przeczytać wszystkie opisy oraz zapoznać się z zasadami używania
> repozytorium.
> Proszę docommitować zmiany i wtedy sprawdzę co jeszcze tu trzeba dalej
> poprawić.
> W pamiętniku zostawiłem komentarz o uzyskiwaniu podwyższonych uprawnień.
> Proszę sprawdzić w Internecie jakie to proste i faktycznie poszukać
> uzasadnienia (być może na superuser/poweruser lub serverfault bądź innych
> temu podobnych) dlaczego zbyt wysokiem uprawnienia są złe.
> Poproszę gdzieś i pozostawienie linków do takich znalezisk. Przydadzą się
> na kolejne zajęcia (dla następnego rocznika) + będą dobrym tematem do
> poszerzenia swojej wiedzy i świadomości o uprawnieniach.
> ------------------------------
>
> In s32351-pj-BartoszWaszczyk/1_Wstep do konsoli_zadania_1.txt
> <https://github.com/t0meck-pj/ukos2023-24_14c/pull/28#discussion_r1424628112>
> :
>
> > @@ -0,0 +1,55 @@
> +1. Uruchom terminal.
> + - no uruchamiam, jako terminal uruchomiłem sobie PowerShell. A co! i łąduję się na szuflandię, ssh ***@***.***
> +
> +2. Wyświetl zawartość aktualnego katalogu.
> + - A włączyłem midnight commander, skrót mc. Acha, ćwiczymy CLI, no to exit (żeby wyjść z MC) i potem na przykład: ls -lA. Duże A, żeby nie było kropeczek.
>
> F10
> ------------------------------
>
> In s32351-pj-BartoszWaszczyk/1_Wstep do konsoli_zadania_1.txt
> <https://github.com/t0meck-pj/ukos2023-24_14c/pull/28#discussion_r1424628441>
> :
>
> > @@ -0,0 +1,55 @@
> +1. Uruchom terminal.
> + - no uruchamiam, jako terminal uruchomiłem sobie PowerShell. A co! i łąduję się na szuflandię, ssh ***@***.***
> +
> +2. Wyświetl zawartość aktualnego katalogu.
> + - A włączyłem midnight commander, skrót mc. Acha, ćwiczymy CLI, no to exit (żeby wyjść z MC) i potem na przykład: ls -lA. Duże A, żeby nie było kropeczek.
> +
> +3. Sprawdź gdzie aktualnie się znajdujesz.
> + - no sprawdzam, pwd. odpowiedź: /home/PJWSTK/s32351, no nie dziwne, to mój katalog domowy na Szuflandii. Hejkum-Kejkum!
>
> ... Olo ratuj!
> ------------------------------
>
> In s32351-pj-BartoszWaszczyk/1_Wstep do konsoli_zadania_1.txt
> <https://github.com/t0meck-pj/ukos2023-24_14c/pull/28#discussion_r1424630705>
> :
>
> > @@ -0,0 +1,55 @@
> +1. Uruchom terminal.
> + - no uruchamiam, jako terminal uruchomiłem sobie PowerShell. A co! i łąduję się na szuflandię, ssh ***@***.***
> +
> +2. Wyświetl zawartość aktualnego katalogu.
> + - A włączyłem midnight commander, skrót mc. Acha, ćwiczymy CLI, no to exit (żeby wyjść z MC) i potem na przykład: ls -lA. Duże A, żeby nie było kropeczek.
> +
> +3. Sprawdź gdzie aktualnie się znajdujesz.
> + - no sprawdzam, pwd. odpowiedź: /home/PJWSTK/s32351, no nie dziwne, to mój katalog domowy na Szuflandii. Hejkum-Kejkum!
> +
> +4. Przejdź do katalogu Pulpit za pomocą ścieżki względnej
> + - dochodzę do wniosku, że na szuflandii nie ma katalogu Pulpit. sprawdzam na wszelki upadek, a nuż ktoś dla zabawy wrzucił. MC. a nie, wychodzę z MC, wpisuję find Pulpit. nie wiem jaki param dla ignorowania rozmiaru liter, zatem man find. no dobra, nie znalazłem czegos jak ignore capitals. Ale jest regex. zatem find -regextype perl regex `(?i)pulpit` ... nie podoba mu się 'perl', będzie AWK, podobne. po kilku próbach i błędach związanych ze składnią, dochodzę do: find -regextype awk -regex "(?i)pulpit". Co nie zadowala mnie, bo wykonuje, nic się nie pojawia, co rozumiem, że nie znajduje. Dla testu robię: find -regextype awk -regex "(?i)projects" hmmm. NIE DZIAŁA, sh.... idę na łatwiznę, google, 'bash find ignore capitals'. find -iname pulpit. Nie ma wyników. testuję na projects. działa. znaczy - nie ma pulpitu. No u mnie nie ma pulpitu, bo zaczynam podejrzewać find działa 'w głąb' standardowo. Exit - Wylogowuję się z szuflandii.
>
> Dobrze... no to tak:
> Opis fajny ALE...
> PRIMO!
> https://github.com/t0meck-pj/ukos2023-24_14c/blob/master/README.md -
> zapoznać się z tekstem i poprawić ten wiersz oraz jak widzę sporo kolejnych
>
> Po co grzebać po opcjach find skoro poprzednie polecenie listowało
> wszystkie katalogi i tam można było sprawdzić czy takowy "Pulpit" istnieje?
> Dobrze, że próbowałeś. To się liczy. No i próbowałeś nowego narzędzia. Ale
> zwróć uwagę, że szuflandia to serwer z domyślnym językiem angielskim więc
> zamiast "Pulpit" mógł się pojawić katalog z angielską nazwą. Jak
> wspominałem na zajęciach: Na tym przedmiocie trzeba myśleć!
>
> Anyways.. faktycznie dla nowych studentów już może takiego katalogu nie
> być.
> Nie korzystacie ze srodowiska graficznego więc to zrozumiałe.
> ------------------------------
>
> In s32351-pj-BartoszWaszczyk/1_Wstep do konsoli_zadania_1.txt
> <https://github.com/t0meck-pj/ukos2023-24_14c/pull/28#discussion_r1424644449>
> :
>
> > +- różnicę dopiero czyni cd ../../../../../../, i teraz znajduję się w roocie windowsa, powyżej katalogu C:/
> +
> +11. Przejdź do swojego katalogu domowego za pomocą ścieżki bezwzględnej.
> +- cd c/Users/steam/ i nie, nie powoduje to u mnie żadnych głębszych przemyśleń.
> +
> +12. Zobacz co się stanie jak wpiszesz komendę 'cd /root'. Jak już to zrobisz, zastanów się co się stało. Poszukaj w Internecie.
> +- no w windzie nie ma takiej opcji. Nie chce mi się instalować linucha w virtualboxie, bo mam zamiar dołożyć którąś dystrybucję w bardzo bliskiej przyszłości jako drugi system do tego lapka, więc zamiast tego wejdę na serwerek na AWSie. Odpaliłęm jakieś t2micro, wchodzę kluczem: ssh -i c:\... ... .ppk nie działa. wracam do PowerShell, tam choco install awscli. Tworzę nowy klucz, ściągam, podmieniam w instancji. W zasadzie to ją usuwam, tworzę nową. Wchodzę do instancji ssh -i klucz ***@***.***, jestem. mc - nie ma. muszę pociągnąć. yum search midnight. nie to. yum search mc. jest mc.x86_64 : User-friendly text console file manager and visual shell. to wrzucę od razu. yum install mc. a, su! zatem sudo yum install mc. poszłóo....... ale co ja miałem zrobić? A! cd /root. permition denied. No bo jestem jako user, nie root.
> +
> +13. Zadanie 13 i 14 trzeba wykonać na maszynie wirtualnej lub na fizycznym komputerze. Nie można go zrobić zdalnie na szuflandii.
> +Zobacz, co się stanie, jeśli wciśniesz kombinację klawiszy: Ctrl+Alt+F3
> +Sprawdź w Internecie co się dzieje kiedy używa się takiej kombinacji. W Internecie mogą pojawić się wersje z F1-F6. To de facto to samo.
> +- no tu na tej maszynie i AWS Linux nie działa jak powinno. Generalnie powinna to być zmiana powłoki. przepraszam, nie powłoki, tylko wirtualnej konsoli, a alt+F7 powinno wrócić do X-a.
> + [...]

2023-12-15 15:42 UTC, t0meck-pj commented
Jak już powiedziałem, styl dla mnie jest ok.
Niektóre rzeczy tylko proszę przeredaguj by nie wyglądało to... źle.

Tak. chodziło o 80 znaków w wierszu.

2024-02-02 20:04 UTC, t0meck-pj requested changes

2024-02-02 20:04 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/3_Procesy i strumienie_zadania.txt
> +Jak myślisz, co oznacza znak zapytania w kolumnie 2?
A gdzie odpowiedź na pytanie?

2024-02-02 20:04 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/3_Procesy i strumienie_zadania.txt
> + ja, to i tak ten sam używkownik. Zatem pytanie do eksperta: jak?
Jeśli skopiujesz używając sudo ze swojego katalogu domowego `~/.ssh/authorized_keys` do katalogu domowego nowego usera `/home/nju.../ssh/` to będziesz mógł tym samym kluczem zalogować się na nowego usera.

Czyli:
`ssh -i /ta/sama/sciezka/co/do/normalnego/polaczenia -l nju... adres_ip_servera`

2024-02-02 20:04 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/4_kolokwium_powtorzenie_zadania.txt
> +- cd /tmp/ukos/ala 2 Masz taki układ katalogów, jak wyżej i ciągle jesteś w
Coś tu entery się pokrzaczyły

2024-02-02 20:04 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/4_kolokwium_powtorzenie_zadania.txt
> +- mv /tmp/ukos/kot/ma/ale /tmp/ukos/ala/i źródło (ścieżka absolutna), miejsce
do poprawy

2024-02-02 20:04 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/4_kolokwium_powtorzenie_zadania.txt
> +- mv ../../../kot/ma/ale /tmp/ukos/ala/i 4 Jak zamknąć program, który nie
do poprawy

2024-02-02 20:04 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/4_kolokwium_powtorzenie_zadania.txt
> +- chmod ua-r,g+r właściciel ma pełne uprawnienia, literowa z równasię
jeśli używasz `a` to nie trzeba dodawać `u` bo zawiera się ono w `a`

2024-02-02 20:04 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/4_kolokwium_powtorzenie_zadania.txt
> +- chmod u=rwx HINT: Jakie są uprawnienia początkowe?
Mało. Gdzie reszta rozwiązania?

2024-02-02 20:04 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/4_kolokwium_powtorzenie_zadania.txt
> +- chmod uga= 7 Jak utworzyć plik z listą plików w bieżącym katalogu? Podaj
enter

2024-02-02 20:04 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/4_kolokwium_powtorzenie_zadania.txt
> +- tabem, zawsze :) 9 Jak uruchomić program by nie blokował terminala. Są 2
enter

2024-02-02 20:04 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/pamietnik.txt
> +serwera.
Też się da ale to inna historia wtedy jest. Używane do czego innego. Dla naszych zastosowań wystarczy użytkownik lokalny na maszynie do której się logujesz.

2024-02-04 18:14 UTC, t0meck-pj approved these changes
Zatwierdzam to warunkowo bo nie chcę już wiecej czytać całości. Popraw proszę błędy.

2024-02-04 18:14 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/1_Wstep do konsoli_zadania_1.txt
> +s32351@szuflandia22:/$ find obrazy
Polecenia `find` trzeba umieć używać.

2024-02-04 18:14 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/1_Wstep do konsoli_zadania_1.txt
> + - no nic się nie stało. jestem w tym samym miejscu. eksperymentuję. nic się
Żle. Nie nic się nie stanie tylko bash musi przeliczyć wskazaną ścieżkę.
Finalnie wylądujesz w tym samy miejscu ale bash swoje przeliczyć musi.

Inny przykład na "nic się nie stało"
Jak odpalasz silnik w aucie to też się nic nie dzieje bo auto natychmiast nie zaczyna jechać? Nie. Dzieje się i to sporo. Załącza się instalacja elektryczna. Wtrysk podaje do komory spalania mieszankę. W zależności od typu silnika jest jeszcze świeca podająca iskrę albo przez sprężanie wzrasta temperatura przy tłoku do uzyskania samozapłonu przy zwiększaniu ciśnienia. A to się zwiększa przez ruch tłoka a ten z kolei jest napędzany rozrusznikiem, który jest zailany z instalacji elektrycznej.

2024-02-04 18:14 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/4_kolokwium_powtorzenie_zadania.txt
> +- mv /tmp/ukos/kot/ma/ale /tmp/ukos/ala/
Tu wciąż nie poprawione

2024-02-04 18:14 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/4_kolokwium_powtorzenie_zadania.txt
> +- mv ../../../kot/ma/ale /tmp/ukos/ala/i
tu też nie poprawione

2024-02-04 18:14 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/4_kolokwium_powtorzenie_zadania.txt
> +- chmod ua-r,g+r właściciel ma pełne uprawnienia,
Tu jest bład

2024-02-04 18:14 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/4_kolokwium_powtorzenie_zadania.txt
> +- chmod u=rwx
Tu też

2024-02-04 18:14 UTC, t0meck-pj commented on s32351-pj-BartoszWaszczyk/4_kolokwium_powtorzenie_zadania.txt
> +- chmod uga=
I tu

2024-02-04 18:15 UTC, merged