s31175-PiotrTrybala rozwiazanie cz1 lab1
t0meck-pj/ukos2023-24_14c pull request #9
Opened 2023-10-26 21:40 UTC by s31175-pj

Przepraszam za opóźnienia, dopiero rozwiązałem problem z dodawaniem klucza ssh oraz commitem

2023-10-26 22:18 UTC, s31175-pj commented
Rozwiązanie części 2giej zadań z Lab1. Wszystkie pliki w poprzednim PR były już "na miejscu", wynika to z tego, że najpierw wykonałem zadania, a dopiero teraz napisałem rozwiązanie w pliku i zacommitowałem.

2023-10-28 13:47 UTC, t0meck-pj requested changes

2023-10-28 13:47 UTC, t0meck-pj commented on s31175-PiotrTrybala/lab1-rozwiazanie
> +Przenioslo mnie do tego samego katalogu
To zadanie jest wykonane błędnie. Do poprawy lub do konsultacji na zajęciach.

2023-10-28 13:47 UTC, t0meck-pj commented on s31175-PiotrTrybala/lab1-rozwiazanie
> +7. ls /$home
Znowu do poprawy lub konsultacji

2023-10-28 13:47 UTC, t0meck-pj commented on s31175-PiotrTrybala/lab1-rozwiazanie
> +Nie mialem katalogu Obrazu w katalogu domowym
Przeczytaj jeszcze raz treść zadania.

2023-10-28 13:47 UTC, t0meck-pj commented on s31175-PiotrTrybala/lab1-rozwiazanie
> +12. cd/root
Tu jest błąd.

2023-10-28 13:47 UTC, t0meck-pj commented on s31175-PiotrTrybala/lab2-rozwiazanie
> +//Wyczytalem ze wykonuje sie operacja AND, ale nie rozumiem czemu.
Internet i szukaj. To jest "studiowanie". W życiu często będzie sytuacja taka, że dostaniesz zadanie ale nie będziesz miał pojęcia jak je wykonać i będziesz musiał "przestudiować" zagadnienie by zrozumieć co masz zrobić. Tu jest podobnie.
Tego typu zadania mają studentów przyzwyczaić do szukania i pogłębiania wiedzy.

Natomiast powiem, że samo AND to mało i z matematycznego punktu widzenia to nie ma prawa zadziałać.

2023-10-28 13:47 UTC, t0meck-pj commented on s31175-PiotrTrybala/ukos/to/jest/dluga/nazwa/dane.txt
Nie ma sensu commitować do repozytorium pustych plików.

2023-10-28 13:47 UTC, t0meck-pj commented on s31175-PiotrTrybala/lab1-rozwiazanie_cz2
> +(cd $home)
Tu jest błąd.
Zmienna `$home` nie istnieje domyślnie.

2023-10-28 13:47 UTC, t0meck-pj commented on s31175-PiotrTrybala/lab1-rozwiazanie
> +13. Podane skroty otwieraja rownolegle sesje, bez zamykania poprzednich
Opis rozwiązań zadań 13 i 14 jest zbyt ogólnikowy a przez to niedokładny.

2023-11-18 02:20 UTC, t0meck-pj approved these changes

2023-11-18 02:20 UTC, merged